### PR TITLE
Missing enums in generated files

### PR DESCRIPTION
**Pull request by guw**
I'm investigating a delta in the generated BridgeSupport files. I'm stuck at some missing enums. I wonder why they are missing. Is it an issue with the tool or in the command line?

Thanks a ton!
## Files
- `AppKit.bridgesupport-found-in-system` found in `/System/Library/Frameworks/AppKit.framework/Resources/BridgeSupport`
- `AppKitFull.bridgesupport-generated` generated s described [here](https://gist.github.com/Watson1978/bc1a8216678905f924bb5c6ee85791ec#file-gistfile1-txt-L7)
## Missing enums

Found in the original one, but missing in the generated one:

```
#AppKit
<enum name='NSStatusWindowLevel' value='25'/>
<enum name='NSSubmenuWindowLevel' value='3'/>

#Foundation
<enum name='NSNotFound' value='2147483647' value64='9223372036854775807'/>
```

### CODE REVIEW

**Comment by Watson1978** [comment]
Sorry, I can't understand what is this.
Looks for me that `NSStatusWindowLevel` or `NSSubmenuWindowLevel` are generated properly.

**Comment by guw** [comment]
@Watson1978 I'm sorry. I'll try to be more clear. This pull-request is not a code change. It documents an issue I'm having. No need to merge it.

I've attached the generated `AppKitFull.bridgesupport-generated` file. This does not contain the `NSStatusWindowLevel` or `NSSubmenuWindowLevel` enum.

Do you have an idea why they would be missing?

**Comment by Watson1978** [comment]
I don't know what you used option when generate it.
But, the values are generated properly.

```
$ RUBYLIB=./DSTROOT/System/Library/BridgeSupport/ruby-2.0 gen_bridge_metadata --format complete --cflags "-I. -isysroot / -mmacosx-version-min=10.12 -DTARGET_OS_MAC=1 -D__ENVIRONMENT_MAC_OS_X_VERSION_MIN_REQUIRED__=101200 -F/System/Library/Frameworks -framework AppKit " --framework /System/Library/Frameworks/AppKit.framework > ~/tmp/AppKit.bridgesupport

$ grep NSStatusWindowLevel ~/tmp/AppKit.bridgesupport
<enum name='NSStatusWindowLevel' value='25'/>
$ grep NSSubmenuWindowLevel ~/tmp/AppKit.bridgesupport
<enum name='NSSubmenuWindowLevel' value='3'/>
```

**Comment by guw** [comment]
Thanks. That is weird. Could there be an issue on my Mac? I just tried on a second Mac and I do get the enums as well. Sorry for bothering and thanks a lot for your help!

**Comment by guw** [comment]
@Watson1978 So I was able to get the enums for AppKit. However, there is another issue with `NSNotFound` and Foundation. The generator seems to generate a constant, while the system one is an enum. 

```
$ RUBYLIB=./DSTROOT/System/Library/BridgeSupport/ruby-2.0 gen_bridge_metadata --format complete --cflags "-I. -isysroot / -mmacosx-version-min=10.12 -DTARGET_OS_MAC=1 -D__ENVIRONMENT_MAC_OS_X_VERSION_MIN_REQUIRED__=101200 -F/System/Library/Frameworks -framework Foundation " --framework /System/Library/Frameworks/Foundation.framework > Foundation.bridgesupport

$ grep NSNotFound Foundation.bridgesupport
<constant const='true' declared_type='NSInteger' name='NSNotFound' type='i' type64='q'/>

$ grep NSNotFound /System/Library/Frameworks/Foundation.framework/Resources/BridgeSupport/Foundation.bridgesupport
<enum name='NSNotFound' value='2147483647' value64='9223372036854775807'/>
```

Any thoughts?

**Comment by Watson1978** [comment]
Please report your issue to Apple.
Because `NSNotFound` is defined as `constant` in OSX 10.12 Foundation.framework.

```
$ ag NSNotFound /System/Library/Frameworks/Foundation.framework
...
/System/Library/Frameworks/Foundation.framework/Versions/C/Headers/NSObjCRuntime.h
545:static const NSInteger NSNotFound = NSIntegerMax;
```

**Comment by Watson1978** [comment]
Actually, OSX bundled BridgeSuppport uses too old clang (maybe clang 2.8 or older) to parse C-lang header.

It has many problem, because to parse recently Objective-C, we need a newer clang.
so we have to do maintenance `BridgeSuppport`  by ourselves.

**Pull request closed without merging**
